version: '3'
services:
  rabbitmq:
    container_name: "rabbitmq"
    image: heidiks/rabbitmq-delayed-message-exchange
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      # Rabbitmq instance
      - '5672:5672'
      # web interface
      - '15672:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
#执行下面的命令 才把 上面的网络映射搞定
#net stop hns
#net start hns
volumes:
  rabbitmq_data: